env:
  node: true
  commonjs: true
  es2020: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  accessor-pairs: error
  array-bracket-newline: error
  array-bracket-spacing: error
  array-callback-return: error
  array-element-newline: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  brace-style: error
  callback-return: error
  capitalized-comments: error
  class-methods-use-this: error
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  complexity: 
    - warn
    - 50
  computed-property-spacing: error
  consistent-return: error
  consistent-this: error
  curly: error
  default-case: error
  default-case-last: error
  default-param-last: error
  dot-location: 
    - error
    - property
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-name-matching: error
  func-names: error
  func-style: 
    - warn
    - declaration
  function-paren-newline: error
  generator-star-spacing: error
  grouped-accessor-pairs: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-denylist: error
  id-length: warn
  id-match: error
  implicit-arrow-linebreak: error
  indent: error
  init-declarations: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-around-directive: error
  lines-between-class-members: error
  max-classes-per-file: error
  max-depth: error
  max-len: 
    - warn
    - 100
  max-nested-callbacks: error
  max-params: error
  max-statements-per-line: error
  multiline-comment-style: error
  multiline-ternary: 
    - warn
    - always-multiline
  new-cap: error
  new-parens: error
  newline-after-var: error
  newline-before-return: error
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-buffer-constructor: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-constructor-return: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-loss-of-precision: error
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-in-lhs: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-process-exit: error
  no-promise-executor-return: error
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-spaced-func: error
  no-sync: 
    - error
    - { allowAtRootLevel: true }
  no-tabs: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: 
    - warn
    - {"skipBlankLines":true}
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-expressions: error
  no-unused-vars: warn
  no-use-before-define: 
    - error
    - nofunc
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: error
  object-property-newline: error
  object-shorthand: error
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: 
    - warn
    - before
  padded-blocks: error
  padding-line-between-statements: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-named-capture-group: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: error
  quotes:
    - error
    - double
  radix: error
  require-atomic-updates: warn
  require-jsdoc: warn
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  semi-style:
    - error
    - last
  space-before-blocks: error
  space-before-function-paren: error
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc:
    - warn
    - {
        requireReturn: false, 
        requireParamDescription: false, 
        requireReturnDescription: false
        }
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda: error