version: "3"
services: 
    blasebot: 
        build: . 
        image: nodejs:17
        container_name: blasebot_instance
        restart: unless-stopped
        env_file: stack.env
        environment: 
            dbUrl: mongodb://database/blasebot
        volumes: 
            - node_modules:/app/node_modules
        depends_on: 
            - database
    database:
        image: mongo:4.1.8-xenial
        container_name: blasebot_database
        restart: unless-stopped
        volumes:
            - dbdata:/data/db

volumes:
  dbdata:
  node_modules:
