name: Build and push
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: chetan/git-restore-mtime-action@v1
            - uses: docker/setup-buildx-action@v1
            - uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ghcr.io/blasebot
                  cache-from: type=gha
                  cache-to: type=gha,mode=max